apiVersion: v1
kind: Pod
metadata:
  name: tool-pod
  labels:
    app: tool
spec:
  containers:
  - name: pod-alpine
    image: alpine
    command: ["/bin/sh"]
    args: ["-c", "apk add --update --no-cache curl apache2-utils && sleep 28800"]
  # - name: node-exporter
  #   image: quay.io/prometheus/node-exporter
  #   args:
  #     - --web.listen-address=0.0.0.0:9101
  #     - --collector.disable-defaults
  #     - --collector.tcpstat
    resources:
      limits:
        cpu: "100m"
    # ports:
    # - name: metrics
    #   containerPort: 9101